version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-finapp
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: finances
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend-finapp
    restart: always
    ports:
      - '3333:3333'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - ADMIN_PASSWORD=admin123
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/.env:/app/.env

volumes:
  pgdata: